### ISSUE TITLE
Feature Request Review

### ISSUE THREAD

**Issue by mp1pro** [jkrish17/musicplaylistapp#4]
Adding the ability to trigger the search function by pressing enter button will indeed make the app faster to navigate. This will also improve the users experience and interface. it would be a better practice to keep logic out of the render function. Instead put it as a function in the class

```
  handleEnter(event) {
    if(event.keyCode === 13) {
      this.search();
    }
}
```
Then call it from where search is being called

`<input onKeyDown={this.handleEnter}/>`

**Comment by jkrish17** [comment]
Great. Thanks.

**Comment by jkrish17** [comment]
I have modified the changes. thanks
